### ISSUE TITLE
OAS 3.0 Support plans

### ISSUE THREAD

**Issue by malinink** [byjg/php-swagger-test#12]
Is there any plans to implement 3.0 spec support?

**Comment by byjg** [comment]
Hi, 

It is on my roadmap offer support for OAS 3.0 but there is no date to start it until this moment.

**Comment by byjg** [comment]
I added the branch "oas30.0" for handle that.

**Comment by byjg** [comment]
I received the PR #27 . Soon will have OpenApi 3.0. :)

**Comment by byjg** [comment]
Version 2.0.0 of PHP Swagger Test was released with OAS 3.0 support.
