### ISSUE TITLE
Accept "any" json validation

### ISSUE THREAD

**Issue by malinink** [byjg/php-swagger-test#16]
There is an option in Swagger 2.0 that handle any JSON.
That option is described in https://stackoverflow.com/questions/32841298/swagger-2-0-what-schema-to-accept-any-complex-json-value

 It is easy to implement that behavior. I will suggest PR on that.

**Comment by byjg** [comment]
Hi! I added a branch "pullrequest-18" with unit tests for your feature. Could you test please?

**Comment by byjg** [comment]
Release 1.2.5 created!
