### ISSUE TITLE
Extra functionality from the Swagger 2.0 spec

### ISSUE THREAD

**Issue by mlambley** [byjg/php-swagger-test#19]
Good day,

I'm looking at https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#items-object and I notice there's a lot of functionality there which isn't being tested here.

Properties like `maximum`, `minimum`, `maxLength`, `minLength`, `pattern` do not seem to be checked. I have noticed that `enum` is checked, within `SwaggerBody->matchString`.

Are there any plans to implement the remaining specification? I'm happy to contribute to this project if you're willing to accept my help. I'll put together details of my proposed change and then go from there.

Thanks.

**Comment by byjg** [comment]
Hi!

There is no plan to implement this by myself but I would appreciate your help. You will help a lot this project by adding new features. Your help is welcome!!!!

**Comment by mlambley** [comment]
Alright I had a chat with my supervisor he would prefer me to make my own project which is aimed at Codeception (rather than PHPUnit) but once that's up and running we can strip out the guts and create a PR for you. It won't be any time soon but I'll let you know.
