### ISSUE TITLE
SwaggerTestCase->assertRequest locked onto specific to that test schema

### ISSUE THREAD

**Issue by Onekone** [byjg/php-swagger-test#24]
This causes issue of being unable to toggle "Allow Null Values" and failing the test.

Using Swagger 2.0 JSON file format

**Comment by byjg** [comment]
Could you be more specific by providing some example?

**Comment by byjg** [comment]
Hello, for some unexplained reason I missed your answer. I am sorry for that. So, for this issue I am adding the possibility of you override the SwaggerSchema. 

Your code now could be:

```php
<?php
public function testGetBook()
    {
        $schema = new SwaggerSchema(.......)

        $this->request
            ->withSwaggerSchema($schema)
            ->withMethod('GET')
            ->withPath('/bookinfo');
        try {
            $response = $this->assertRequest($this->request);
        } catch (\Exception $e) {
            $this->fail('Failed - ' . $e->getMessage());
        }
    }
```

You do need call `->send()` because the `assertRequest()` already do this.

**Comment by byjg** [comment]
Merged to branch `oas30`
