### ISSUE TITLE
A required request body will not fail tests, if no body is given

### ISSUE THREAD

**Issue by Zeromax** [byjg/php-swagger-test#3]
Hello there, thanks for this great package.

I have the following problem: If I have a required request body (defined in swagger), but non is given in my test, then the test does not fail.
I expected that the test will fail.

This seems to be a bug:
https://github.com/byjg/php-swagger-test/blob/master/src/SwaggerTestCase.php#L80-L82

I think in `SwaggerRequestBody` the exception should only be thrown if `$body` is not empty and no parameter body is found.

**Comment by byjg** [comment]
Hi, 

FIrst of all, thank you :)

I believe you are right. I'll found some time to touch in the code this week and fix it. Meanwhile, If you have some idea or piece of code it will welcome.

**Comment by Zeromax** [comment]
Thanks for the fast reply.

My workaround at the moment:
```php
$bodyRequestDef = $this->swaggerSchema->getRequestParameters($expectedResponse->path, $expectedResponse->method);
try {
    $bodyRequestDef->match($requestBody);
} catch (InvalidDefinitionException $e) {
    if ('There is no body for match' !== $e->getMessage()) {
        // throw exception if not the body exception
        throw $e;
    }
    if ('There is no body for match' === $e->getMessage() && !empty($content)) {
        // throw exception if there is no body in swagger, but a body given
        throw $e;
    }
}
```

But I really think there is a better solution ;)

**Comment by byjg** [comment]
Yeah, I'll figure it out a way inside the library.

Probably today at night I'll have a draft solution,

**Comment by byjg** [comment]
I did a fix. I'd like you test if before I merge it . 

In your composer.json do it:

```
{
    "require": {
        "byjg/swagger-test": "1.1.0.x-dev"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

**Comment by Zeromax** [comment]
That's perfect. Thanks for this fast fix!

**Comment by byjg** [comment]
I published a new release.
