### ISSUE TITLE
Variables in servers object

### ISSUE THREAD

**Issue by VonSerpe** [byjg/php-swagger-test#31]
When I use variables inside URL, the library doesn't make substitution.
This is an example

```json  
"servers": [
    {
      "url": "https://{environment}.domain.com{basePath}",
      "description": "My API server",
      "variables": {
        "environment": {
          "enum": [
            "www",
            "stage"
          ],
          "default": "www"
        },
        "basePath": {
          "default": "/api/v2"
        }
      }
    }
]
```

[This is a link on OpenAPI3 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#server-object).

**Comment by byjg** [comment]
Hello, thank you for let me know it. I'll take a look on this.

**Comment by byjg** [comment]
Done! PR #32 . Soon I will create a version number.

**Comment by byjg** [comment]
Tag `2.0.1` released.
