### ISSUE TITLE
nullable value matching

### ISSUE THREAD

**Issue by estaton** [byjg/php-swagger-test#37]
Hi,

I have a definition of an object with property:
```json
"activity": {
  "$ref": "#/definitions/Activity"
},
```
and this property is not set as required.
When I match a response ({"activity": null}) with that schema, I got an error: "Value of property '#/definitions/Activity' is null, but should be of type 'object'"

yeah, I know, in general, I wrote, that activity is an object, but because OpenApi 2.0 (Swagger) doesn't support any kind of "nullable" definition, do you have any idea how can I test such response?

**Comment by byjg** [comment]
The Swagger specification (OpenAPI 2.0) does not support nullable. To solve this we added to `SwaggerSchema` the parameter `allowNullValues`. 

e.g.
```
$schema = new SwaggerSchema($jsonFile, $allowNullValues)
```

More details on issue #6

**Comment by estaton** [comment]
thank you very much, works like a charm :D
