### ISSUE TITLE
Typo: getDefintion should be getDefinition

### ISSUE THREAD

**Issue by UlrichEckhardt** [byjg/php-swagger-test#39]
Just a typo. I found this in the version3 branch which I'm currently evaluating.

**Comment by byjg** [comment]
Good catch. That type of typo is really hard to identify. It was fixed on `version3` branch.

Thank you.

**Comment by UlrichEckhardt** [comment]
Thank you for the quick fix!

Just wondering, what are your release plans for version 3, both in time and features? The reason I'm asking is that I'm currently trying to integrate it into an existing project and that I'd like to propose a few changes as well. I have forked the repo for now, so I can work on it and publish that for discussion, but ultimately I don't want to maintain it forever.

The topics I'm adressing are:
- PHP 7.4 support. It's probably just adding a line to `.travis.yml`.
- Legacy PHP (5.6, 7.0, maybe 7.1) support. I'd tend to drop this, which then also allows further type annotations in code.
- Support for Codeception (test metaframework). The problem is that with Codeception, the baseclass is given (it itself derives from PHPUnit's TestCase), so you can't use `ApiTestCase`. As alternative, I have extracted the relevant code into a trait.
- Support for YAML schema files. Some people find them friendlier to read. However, using them doesn't work at the moment, because some code requires a filename and only supports JSON for decoding it.
- Support for not sending actual HTTP requests. We're trying to avoid sending actual requests, which brings the need to start a server process with an available network port and complicates debugging a bit. The approach I have running in a prototype splits between the request/response validation and the actual message exchange, so that the latter can also be done inside the same process.

**Comment by byjg** [comment]
Awesome!! The help will be very welcome!

I have some considerations: 

> Drop the support for Legacy PHP (5.6, 7.0, maybe 7.1)

I know PHP 7.2 and higher are better and PHP is becoming a "real" language, however it is a number of people still not migrate from PHP 5.6. 

If it is possible, please let's consider mantain. Probably a good strategy is merge the OpenAPI 3.0 with PHP5.6 and then drop the support in a new version. 

 > Support for not sending actual HTTP requests. 

I like the idea. Instead just replace is it possible to create a new class to handle this?

**Comment by UlrichEckhardt** [comment]
Concerning the last point, I backported the code to `master` and opened a PR.

**Comment by byjg** [comment]
That issue grows and was handled in the PR:

- Fix bug in request processing #45 
- Version3 refactor ApiTestCase #44
- YAML support #43
- Some small issues #42
- Optional HTTP transport for version3 #41 

Closing this issue.
