### ISSUE TITLE
PHP 8 Compatibility

### ISSUE THREAD

**Issue by casingh1990** [byjg/php-swagger-test#64]
Seems like some dependencies do not have PHP 8 support.

```  Problem 1
    - byjg/swagger-test[3.1.0, ..., 3.1.2] require byjg/webrequest 2.0.* -> satisfiable by byjg/webrequest[2.0.0, 2.0.1].
    - byjg/webrequest[2.0.0, ..., 2.0.1] require mintware-de/streams 1.0.* -> satisfiable by mintware-de/streams[v1.0.0, v1.0.1].
    - mintware-de/streams[v1.0.0, ..., v1.0.1] require php 5.6.* || ^7.0 -> your php version (8.0.6; overridden via config.platform, same as actual) does not satisfy that requirement.
    - Root composer.json requires byjg/swagger-test 3.1.* -> satisfiable by byjg/swagger-test[3.1.0, 3.1.1, 3.1.2].
```

This is a request to have these appropriately updated to versions that supports PHP 8.

**Comment by byjg** [comment]
Thank you for the heads up. I am figuring out how to fix that since it is using a 3rd party library.

**Comment by vitormattos** [comment]
Hi @byjg ,
Can I take on this mission of making the project compatible with PHP8?

**Comment by byjg** [comment]
Hey @vitormattos, 

Awesome, have you help me with this. I saw your PRs. I am analyzing them and merge in the next few days.

**Comment by byjg** [comment]
Hello @casingh1990, I created a version that is compatible with PHP 8.0. So you can just `composer update` to get the new version. 

I am working in the @vitormattos PR #65 and #66 to get a fully PHP 8.0 version and close this issue.

**Comment by casingh1990** [comment]
Thank you. the latest pull looks great!
