### ISSUE TITLE
Fatal error while trying to Unset non existing key in array 

### ISSUE THREAD

**Issue by wilvers** [byjg/php-swagger-test#9]
abstract class SwaggerBody
Fatal error: Cannot unset string offsets in vendor\byjg\swagger-test\src\SwaggerBody.php on line 164

first the key is tested if exist and unset if not exist
```
if (!array_key_exists($prop, $body)){
    if ($required !== false) {
      throw new NotMatchedException("Required property '$prop' in '$name' not found in object");
   }
// it's useless to unset non existing key 
   unset($body[$prop]);
  continue;
}
```

**Comment by byjg** [comment]
yes, that's make sense. do you have a swagger.json file and a case where this happened?

**Comment by wilvers** [comment]
HI, 
I create a test generator to validate the response and swagger definition in order to generate an API client.
Below you will find the Json Response and swagger definition (just part of the swagger file of 14000 lines).

**api response :**
{
	"isoCode":"fr",
	"label":"Version fran\u00e7aise",
	"isDefault":true
},
{
	"isoCode":"nl",
	"label":"Nederlandstalige versie",
	"isDefault":false
},
{
	"isoCode":"en",
	"label":"English version",
	"isDefault":false
}

**swagger definition :**  
**Paths :** 

    "/languages" : {
      "get" : {
        "tags" : [ "general" ],
        "summary" : "Get list of languages details for the specified site",
        "consumes" : [ "text/plain; charset=utf-8" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "site",
          "in" : "query",
          "description" : "Application context<br />\nExample: 'sl'\n",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "JSON object",
            "schema" : {
              "type" : "array",
              "description" : "languages result",
              "items" : {
                "$ref" : "#/definitions/LanguageData"
              }
            }
          },
          "400" : {
            "description" : "Bad request",
            "schema" : {
              "$ref" : "#/definitions/ErrorModel"
            }
          },
          "404" : {
            "description" : "Not found",
            "schema" : {
              "$ref" : "#/definitions/ErrorModel"
            }
          },
          "500" : {
            "description" : "Error",
            "schema" : {
              "$ref" : "#/definitions/ErrorModel"
            }
          }
        }
      }
    }
	
**Definitions :** 

    "LanguageData" : {
      "type" : "array",
      "description" : "Languages data",
      "items" : {
        "$ref" : "#/definitions/LanguageData_inner"
      }
    },
    "LanguageData_inner" : {
      "properties" : {
        "isoCode" : {
          "$ref" : "#/definitions/Language"
        },
        "label" : {
          "type" : "string",
          "description" : "Language label in extracted language"
        },
        "isDefault" : {
          "type" : "boolean",
          "description" : "Is the default language for the site"
        }
      }
    },
    "Language" : {
      "type" : "string",
      "description" : "Language ISO 639-1 (2 characters)",
      "example" : "fr"
    },

**Comment by byjg** [comment]
Thank you. I'll take a look.

**Comment by byjg** [comment]
Hi, 

I found the error. There is a problem in the swagger json definition and/or request data. 

Your response 200 (below)

```json
"responses" : {
  "200" : {
    "description" : "JSON object",
    "schema" : {
      "type" : "array",
      "description" : "languages result",
      "items" : {
         "$ref" : "#/definitions/LanguageData"
      }
   }
}
```
expects an array of LanguageData; and LanguageData expects an array of LanguageData_inner

Probably if you are doing a request like this:

```json
[
   {
      "isoCode":"fr",
      "label":"French",
      "isDefault":true
   },
   {
      "isoCode":"br",
      "label":"Brazilian",
      "isDefault":false
   }
]
```

Will cause the fatal error, because, in fact, the Swagger Schema expects one more array level. 

So, there is two ways for you fix that:

1) Fix your response definition by removing the "Items" property as you can see below:

```json
"responses" : {
  "200" : {
    "description" : "JSON object",
    "schema" : {
      "type" : "array",
      "description" : "languages result",
      "$ref" : "#/definitions/LanguageData"
   }
}
```

OR

2) Change your request to match with your original response definition:

```json
[
   [
      {
         "isoCode":"fr",
         "label":"French",
         "isDefault":true
      },
      {
         "isoCode":"br",
         "label":"Brazilian",
         "isDefault":false
      }
   ]
]
```

Anyway, I created a validation to check if the request is matching with the definition and throw a specific error message "InvalidRequestException".

I created also a new swagger json file and two test cases to enforce this. 

Please, check it and give a feedback.

Thank you.

**Comment by byjg** [comment]
Hello, 

Just checking if you received the message. 

I plan release a new version and would like to include your issue in that. Let me know.

**Comment by wilvers** [comment]
Hi,
Strange, I commented on your last message and I can not find my comment!
This fix looks good. I will give you feedback in the following days.

**Comment by byjg** [comment]
thank  you!
